# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20180831_1617'),
        ('reglogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(related_name='users', to='travel.Trip'),
        ),
    ]
