# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0002_user_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trips',
        ),
    ]
