# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
        ('travel', '0004_auto_20180830_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travelers',
        ),
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='trips', to='reglogin.User'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourist_destination',
            field=models.ManyToManyField(related_name='tourists', to='travel.Trip'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='tourists',
            field=models.ManyToManyField(related_name='tourists', to='reglogin.User'),
        ),
    ]
