# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180831_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='tourists',
            field=models.ManyToManyField(to='reglogin.User'),
        ),
    ]
