# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0003_remove_user_trips'),
        ('travel', '0008_auto_20180831_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='trips', to='reglogin.User'),
        ),
    ]
