# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0003_remove_user_trips'),
        ('travel', '0009_trip_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reglogin.User'),
        ),
    ]
