# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20180831_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(to='reglogin.User'),
        ),
    ]
