# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20180901_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='travelers', to='reglogin.User'),
        ),
    ]
